# Site settings
title: Goncharko Law
email: stasia@goncharkolaw.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "goncharkolaw.com"

twitter_username:
github_username:

# Build settings
markdown: kramdown
